AWSTemplateFormatVersion: "2010-09-09"
Description: Create an ECR repository for the project

Parameters:
  RepositoryName:
    Type: String
    Default: test-docker-123

Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 20 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 20
                },
                "action": { "type": "expire" }
              }
            ]
          }

Outputs:
  RepoUri:
    Description: Full URI of the ECR repository
    Value: !GetAtt EcrRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-RepoUri"
