AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Cluster, Task Definition, and Service for Docker container

Parameters:
  ClusterName:
    Type: String
    Default: MyEcsCluster
    Description: Name of the ECS Cluster

  ServiceName:
    Type: String
    Default: MyEcsService
    Description: ECS Service Name

  ContainerName:
    Type: String
    Default: my-container
    Description: Name of the container

  ContainerPort:
    Type: Number
    Default: 8080
    Description: Port exposed by the container

  DesiredCount:
    Type: Number
    Default: 1
    Description: Number of ECS tasks to run

  Cpu:
    Type: String
    Default: 256
    Description: CPU units for the task

  Memory:
    Type: String
    Default: 512
    Description: Memory for the task in MiB

  ImageUri:
    Type: String
    Description: Full image URI in ECR, e.g. 123456789012.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest

Resources:

  MyCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ClusterName}-TaskDefinition"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      ExecutionRoleArn:
        Fn::ImportValue: my-iam-stack-ECSExecutionRoleArn
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref ImageUri
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp

  MyServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue: my-vpc-stack-VpcId
      GroupDescription: Security group for ECS service
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: ECS-Service-SG

  MyService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      ServiceName: !Ref ServiceName
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Fn::ImportValue: my-vpc-stack-PublicSubnet1Id
            - Fn::ImportValue: my-vpc-stack-PublicSubnet2Id
          SecurityGroups:
            - !Ref MyServiceSecurityGroup
      TaskDefinition: !Ref MyTaskDefinition

Outputs:
  ECSClusterName:
    Description: Name of the ECS Cluster
    Value: !Ref MyCluster
    Export:
      Name: !Sub "${AWS::StackName}-ClusterName"

  ECSServiceName:
    Description: Name of the ECS Service
    Value: !Ref MyService
    Export:
      Name: !Sub "${AWS::StackName}-ServiceName"
