AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Cluster (EC2 launch type) with ASG capacity provider – no SSH key"

########################################
# PARAMETERS
########################################
Parameters:
  ECSClusterName:
    Type: String
    Default: html-ecs
    Description: Cluster name
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  Ec2InstanceProfileArn:
    Type: String
  LatestECSAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

########################################
# RESOURCES
########################################
Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound HTTP 8080
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIpv6: "::/0"

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName
      ClusterSettings:
        - Name: containerInsights
          Value: disabled

  ECSLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    DependsOn: ECSCluster
    Properties:
      LaunchTemplateData:
        ImageId: !Ref LatestECSAMI
        InstanceType: t3.micro
        IamInstanceProfile: { Arn: !Ref Ec2InstanceProfileArn }
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs: { VolumeSize: 30 }
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            DeleteOnTermination: true
            Groups: [ !GetAtt EC2SecurityGroup.GroupId ]
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo ECS_CLUSTER=${ECSClusterName} >> /etc/ecs/ecs.config

  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: ECSCluster
    Properties:
      VPCZoneIdentifier: !Ref SubnetIds
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      LaunchTemplate:
        LaunchTemplateId: !Ref ECSLaunchTemplate
        Version: !GetAtt ECSLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: !Sub "ECS Instance - ${ECSClusterName}"
          PropagateAtLaunch: true

  AsgCapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      Name: !Sub "${ECSClusterName}-cp"
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref ECSAutoScalingGroup
        ManagedScaling: { Status: ENABLED, TargetCapacity: 100 }
        ManagedTerminationProtection: DISABLED

  ClusterCPAssociation:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    DependsOn: ECSCluster
    Properties:
      Cluster: !Ref ECSCluster
      CapacityProviders: [ !Ref AsgCapacityProvider ]
      DefaultCapacityProviderStrategy:
        - Base: 0
          Weight: 1
          CapacityProvider: !Ref AsgCapacityProvider

########################################
# OUTPUTS
########################################
Outputs:
  ClusterArn:
    Description: ARN of ECS cluster
    Value: !Ref ECSCluster
    Export: { Name: !Sub "${AWS::StackName}-ClusterArn" }

  ClusterName:
    Description: Cluster name
    Value: !Ref ECSClusterName
    Export: { Name: !Sub "${AWS::StackName}-ClusterName" }

  CapacityProviderName:
    Description: ASG capacity provider name
    Value: !Ref AsgCapacityProvider
    Export: { Name: !Sub "${AWS::StackName}-CapacityProvider" }

  EC2SecurityGroupId:                      # 🆕
    Description: SG ID for cluster hosts
    Value: !Ref EC2SecurityGroup
    Export: { Name: !Sub "${AWS::StackName}-EC2SecurityGroupId" }
