AWSTemplateFormatVersion: "2010-09-09"
Description: IAM roles and profiles for ECS (execution role, task role, instance profile)

Parameters:
  ECSExecutionRoleName:
    Type: String
    Default: ECSExecutionRole
  ECSTaskRoleName:
    Type: String
    Default: ECSTaskRole
  ECSInstanceRoleName:
    Type: String
    Default: ECSInstanceRole

Resources:
  # ── 1. Task Execution Role ───────────────────────────
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ECSExecutionRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: ecs-tasks.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # ── 2. Task Role (for app code) ───────────────────────
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ECSTaskRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: ecs-tasks.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DemoAppAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: "*"

  # ── 3. Instance Role / Profile for EC2 hosts ─────────
  ECSInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ECSInstanceRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: ec2.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ !Ref ECSInstanceRole ]

# ── Outputs ─────────────────────────────────────────────
Outputs:
  ECSExecutionRoleArn:
    Description: ARN of ECS Task Execution Role
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECSExecutionRoleArn"

  ECSTaskRoleArn:
    Description: ARN of ECS Task Role
    Value: !GetAtt ECSTaskRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ECSTaskRoleArn"

  ECSInstanceProfileArn:
    Description: ARN of EC2 Instance Profile for ECS hosts
    Value: !Ref ECSInstanceProfile
    Export:
      Name: !Sub "${AWS::StackName}-InstanceProfileArn"
