AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Phase 1 - Create an Amazon ECR Repository for storing Docker container images.

Parameters:
  RepoName:
    Type: String
    Default: my-html-site
    Description: Name of the ECR repository to create

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepoName
      ImageScanningConfiguration:
        scanOnPush: true
      Tags:
        - Key: Environment
          Value: Dev

Outputs:
  RepositoryUri:
    Description: URI of the created ECR repository
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepoName}"
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryUri"
