AWSTemplateFormatVersion: '2010-09-09'
Description: Phase-1 – create a private ECR repository for the HTML site

Parameters:
  RepoName:
    Type: String
    Default: my-html-site          # change if you like
    Description: Name of the ECR repository

Resources:
  HtmlRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepoName
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: false

Outputs:
  RepositoryUri:
    Value: !GetAtt HtmlRepo.RepositoryUri
    Description: URI you’ll push the Docker image to
