AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Service with EC2 launch type and managed network configuration

Parameters:
  ClusterName:
    Type: String
    Description: Name of the ECS Cluster

  ServiceName:
    Type: String
    Default: html-ecs-service
    Description: Name of the ECS Service

  TaskDefinitionArn:
    Type: String
    Description: ARN of the ECS Task Definition

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs for the ECS service

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID to associate with the ECS tasks

  CapacityProviderName:
    Type: String
    Description: Name of the capacity provider associated with the ECS cluster

Resources:
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      ServiceName: !Ref ServiceName
      TaskDefinition: !Ref TaskDefinitionArn
      DesiredCount: 1
      LaunchType: EC2
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref SecurityGroupId
      CapacityProviderStrategy:
        - CapacityProvider: !Ref CapacityProviderName
          Weight: 1
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: false  # prevent premature task stop if app takes time
          Rollback: false
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      EnableECSManagedTags: true
      PropagateTags: SERVICE

Outputs:
  ECSServiceName:
    Description: Name of the ECS Service
    Value: !Ref ECSService
    Export:
      Name: !Sub "${AWS::StackName}-ServiceName"

  ECSServiceArn:
    Description: ARN of the ECS Service
    Value: !GetAtt ECSService.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ServiceArn"
