AWSTemplateFormatVersion: "2010-09-09"
Description: "Register ECS task definition only (no service created)"

########################################
# PARAMETERS (supplied by deploy-task.yml)
########################################
Parameters:
  ClusterName:
    Type: String
  ImageUri:
    Type: String
  ECSExecutionRoleArn:
    Type: String
  ECSTaskRoleArn:
    Type: String

########################################
# RESOURCES
########################################
Resources:

  TaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ClusterName}-task"
      RequiresCompatibilities: [EC2]
      NetworkMode: awsvpc
      Cpu:    "512"     # 0.5 vCPU
      Memory: "1024"     # 1 GiB
      ExecutionRoleArn: !Ref ECSExecutionRoleArn
      TaskRoleArn:      !Ref ECSTaskRoleArn
      ContainerDefinitions:
        - Name: html-site
          Image: !Ref ImageUri
          Essential: true
          Cpu: 512
          Memory: 1024
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:  !Sub "/ecs/${ClusterName}"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: site

########################################
# OUTPUTS
########################################
Outputs:
  TaskDefArn:
    Description: ARN of the registered task definition
    Value: !Ref TaskDef
    Export:
      Name: !Sub "${AWS::StackName}-TaskDefArn"
