AWSTemplateFormatVersion: "2010-09-09"
Description: "Register task definition and create ECS service (EC2 launch type)"

########################################
# PARAMETERS (supplied by deploy-task.yml)
########################################
Parameters:
  ClusterName:
    Type: String
  CapacityProviderName:
    Type: String
  ImageUri:
    Type: String
  ECSExecutionRoleArn:
    Type: String
  ECSTaskRoleArn:
    Type: String
  SubnetIds:                 # comma-separated list
    Type: CommaDelimitedList
  EC2SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

########################################
# RESOURCES
########################################
Resources:

  TaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ClusterName}-task"
      RequiresCompatibilities: [EC2]
      NetworkMode: bridge                # matches your EC2 hosts
      Cpu:   "1024"                      # 1 vCPU
      Memory: "1024"                     # 1 GiB
      ExecutionRoleArn: !Ref ECSExecutionRoleArn
      TaskRoleArn:      !Ref ECSTaskRoleArn
      ContainerDefinitions:
        - Name: html-site
          Image: !Ref ImageUri
          Essential: true
          Cpu: 1024
          Memory: 1024
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:  !Sub "/ecs/${ClusterName}"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: site

  Service:
    Type: AWS::ECS::Service
    DependsOn: TaskDef
    Properties:
      ServiceName: !Sub "${ClusterName}-svc"
      Cluster:      !Ref ClusterName
      DesiredCount: 1
      CapacityProviderStrategy:
        - CapacityProvider: !Ref CapacityProviderName
          Weight: 1
      LaunchType: EC2
      TaskDefinition: !Ref TaskDef
      NetworkConfiguration:    # enables awsvpc ENI attach even with bridge mode
        AwsvpcConfiguration:
          Subnets: !Ref SubnetIds
          SecurityGroups: [ !Ref EC2SecurityGroupId ]
          AssignPublicIp: ENABLED
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50

########################################
# OUTPUTS
########################################
Outputs:
  ServiceName:
    Description: Name of ECS service
    Value: !GetAtt Service.Name
    Export: { Name: !Sub "${AWS::StackName}-ServiceName" }

  TaskDefArn:
    Description: ARN of the task definition
    Value: !Ref TaskDef
