AWSTemplateFormatVersion: "2010-09-09"
Description: "Registers a task definition and ECS service (EC2 launch type)"

Parameters:
  # — values fed from GitHub Actions —
  ClusterName:
    Type: String
  CapacityProviderName:
    Type: String
  ImageUri:
    Type: String
  ECSExecutionRoleArn:
    Type: String
  ECSTaskRoleArn:
    Type: String

Resources:
  AppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ClusterName}-task"
      RequiresCompatibilities: [EC2]
      NetworkMode: bridge
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: !Ref ECSExecutionRoleArn
      TaskRoleArn: !Ref ECSTaskRoleArn
      ContainerDefinitions:
        - Name: html-app
          Image: !Ref ImageUri
          Essential: true
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${ClusterName}"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: task

  AppService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "${ClusterName}-svc"
      Cluster: !Ref ClusterName
      DesiredCount: 1
      CapacityProviderStrategy:
        - CapacityProvider: !Ref CapacityProviderName
          Weight: 1
      TaskDefinition: !Ref AppTaskDefinition
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50

Outputs:
  ServiceName:
    Description: ECS service name
    Value: !GetAtt AppService.Name
    Export:
      Name: !Sub "${AWS::StackName}-ServiceName"

  TaskDefArn:
    Description: ARN of task definition
    Value: !Ref AppTaskDefinition
