name: Deploy VPC Stack

on:
  push:
    paths:
      - "infra/vpc.yml"
      - ".github/workflows/deploy-vpc.yml"
      - "scripts/save-outputs.sh"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION:     ${{ secrets.AWS_REGION }}
  STACK_NAME:     my-vpc-stack               # <- keep this fixed
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  deploy-vpc:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Configure AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region:     ${{ env.AWS_REGION }}

      # 3. Deploy or update the VPC stack
      - name: Deploy VPC CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name ${STACK_NAME} \
            --template-file infra/vpc.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      # 4. Collect outputs and push to S3
      - name: Save outputs.txt and upload to S3
        run: |
          chmod +x scripts/save-outputs.sh
          S3_BUCKET_NAME=${{ env.S3_BUCKET_NAME }} \
          ./scripts/save-outputs.sh ${STACK_NAME}

      # 5. Attach outputs.txt as GitHub artifact (optional)
      - name: Upload outputs.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: vpc-outputs
          path: infra/outputs.txt
