name: Deploy VPC Stack

on:
  push:
    paths:
      - "infra/vpc.yml"
      - ".github/workflows/deploy-vpc.yml"
      - "scripts/save-outputs.sh"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      VPC_STACK: my-vpc-stack
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy VPC stack
        run: |
          aws cloudformation deploy \
            --stack-name ${VPC_STACK} \
            --template-file infra/vpc.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Save VPC outputs to outputs.txt
        run: |
          chmod +x scripts/save-outputs.sh
          scripts/save-outputs.sh ${VPC_STACK}

      - name: Upload outputs.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: vpc-outputs
          path: outputs.txt
