name: Deploy IAM Stack

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-iam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy IAM CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name my-iam-stack \
            --template-file infra/iam.yml \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
